project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Visualizing the IBM Quantum Computing Hardware System"
  author:
    - Nrushad Joshi
  repo-url: https://nrushad007.github.io/QuantumComputingDataViz/
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


